# Generated by Django 6.0.3 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
